spring:
  application:
    name: accounts
  profiles:
    active: production
  datasource:
    url: ${accounts.datasource.url}
    username: ${accounts.datasource.username}
    password: ${accounts.datasource.password}
    ddl-auto: ${accounts.datasource.ddl-auto}
# ACTUATOR INFO
info:
  app:
    name: "Accounts"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}
management:
  endpoints:
    web:
      exposure:
        include: '*'
application:
  allow-get-accounts: ${accounts.allow-get-accounts}
